# Generated by Django 5.1.5 on 2025-05-24 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('billid', models.IntegerField()),
                ('sku', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('item_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Restocked', 'Restocked')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('item_brand', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billingapp.bill')),
            ],
        ),
    ]
