# Generated by Django 5.1.5 on 2025-05-24 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product Name', max_length=255)),
                ('category', models.CharField(choices=[('Computers', 'Computers'), ('Networking Devices', 'Networking Devices'), ('CCTV & Surveillance', 'CCTV & Surveillance'), ('Printers & Accessories', 'Printers & Accessories'), ('Peripherals', 'Peripherals'), ('Storage Devices', 'Storage Devices'), ('Hardware Components', 'Hardware Components'), ('Accessories', 'Accessories')], help_text='Product Category', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed Description')),
                ('brand', models.CharField(help_text='Brand or Manufacturer', max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase Price', max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, help_text='18.00', max_digits=4)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling Price including GST', max_digits=10)),
                ('stock', models.PositiveBigIntegerField(default=0, help_text='Items in stock')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('supplier_name', models.CharField(blank=True, help_text='Supplier Name', max_length=100, null=True)),
                ('supplier_id', models.IntegerField(blank=True, help_text='Supplier ID', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product Name', max_length=255)),
                ('category', models.CharField(help_text='Product Category', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed Description')),
                ('brand', models.CharField(help_text='Brand or Manufacturer', max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase Price', max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, help_text='GST%', max_digits=4)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling Price including GST', max_digits=10)),
                ('stock', models.PositiveBigIntegerField(default=0, help_text='Items Purchased')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('supplier_name', models.CharField(blank=True, help_text='Supplier Name', max_length=100, null=True)),
                ('supplier_gstin', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('item_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_gstin', models.CharField(max_length=15, unique=True)),
                ('supplier_address', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('supplier_phone', models.CharField(max_length=10)),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tallyreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.IntegerField()),
                ('total_purchases', models.IntegerField()),
                ('total_purchase_returns', models.IntegerField()),
                ('total_sales_quantity', models.IntegerField()),
                ('total_sales_return', models.IntegerField()),
                ('closing_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
